name: Echo Message

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on  

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a Message
        run: echo "Hello, GitHub Actions!"
